import { DEFAULT_CONFIDENCE_THRESHOLD, DEFAULT_GLOBAL_STRENGTH, DEFAULT_HYSTERESIS, P0_TRIGGER_IDS, SETTINGS_SCHEMA_VERSION, type AudioShieldSettings, type TriggerRule, type TriggerId } from "../shared/settings/types";
export const SETTINGS_STORAGE_KEY = "audioshield.settings";
export interface StorageArea { get(key: string): Promise<Record<string, unknown>>; set(value: Record<string, unknown>): Promise<void>; }
const clamp = (v: unknown, fallback: number) => typeof v === "number" && Number.isFinite(v) ? Math.min(1, Math.max(0, v)) : fallback;
const defaultRules = (): TriggerRule[] => P0_TRIGGER_IDS.map((id) => ({ id, enabled: true, strength: DEFAULT_GLOBAL_STRENGTH }));
export const defaultSettings = (): AudioShieldSettings => ({ schemaVersion: SETTINGS_SCHEMA_VERSION, globalStrength: DEFAULT_GLOBAL_STRENGTH, triggers: defaultRules(), confidenceThreshold: DEFAULT_CONFIDENCE_THRESHOLD, hysteresis: DEFAULT_HYSTERESIS, sitePreferences: {} });
function normalizeRule(value: unknown, id: TriggerId): TriggerRule { const r = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { id, enabled: typeof r.enabled === "boolean" ? r.enabled : true, strength: clamp(r.strength, DEFAULT_GLOBAL_STRENGTH) }; }
export function migrateSettings(value: unknown): AudioShieldSettings { const d = defaultSettings(); if (!value || typeof value !== "object") return d; const r = value as Record<string, unknown>; const old = Array.isArray(r.triggers) ? r.triggers : []; const byId = new Map(old.filter((x): x is Record<string, unknown> => !!x && typeof x === "object").map((x) => [x.id, x])); const sites = r.sitePreferences && typeof r.sitePreferences === "object" ? r.sitePreferences as AudioShieldSettings["sitePreferences"] : {}; return { schemaVersion: SETTINGS_SCHEMA_VERSION, globalStrength: clamp(r.globalStrength, d.globalStrength), triggers: P0_TRIGGER_IDS.map((id) => normalizeRule(byId.get(id), id)), confidenceThreshold: clamp(r.confidenceThreshold, d.confidenceThreshold), hysteresis: clamp(r.hysteresis, d.hysteresis), sitePreferences: sites }; }
export async function loadSettings(storage: StorageArea): Promise<AudioShieldSettings> { try { return migrateSettings((await storage.get(SETTINGS_STORAGE_KEY))[SETTINGS_STORAGE_KEY]); } catch { return defaultSettings(); } }
export async function saveSettings(storage: StorageArea, settings: AudioShieldSettings): Promise<void> { await storage.set({ [SETTINGS_STORAGE_KEY]: migrateSettings(settings) }); }
export function normalizeSiteKey(url: string): string | null { try { const host = new URL(url).hostname.toLowerCase().replace(/^www\./, ""); return host || null; } catch { return null; } }
